name: Quality check.
author: Harshad Hegde <hhegde@lbl.gov>
description: Quality check for a given project.
inputs:
  python-versions:
    description: Python version(s).
  use-tox:
    description: Run tox
    default: "false"
# outputs:
#   random-number:
#     description: Random number
#     value: ${{ steps.random-number-generator.outputs.random-number }}

runs:
  using: "composite"
  steps:
    
    - name: Set up Python ${{ inputs.python-versions }}
      uses: actions/setup-python@v4.3.0
      with:
        python-version: ${{ inputs.python-versions }}

    - name: Install Poetry
      run: pip install poetry
      shell: bash

    - name: Install dependencies
      run: poetry install --no-interaction
      shell: bash
    
    - name: Check code quality, static typing and run tests with tox
      run: poetry run tox
      shell: bash
      if: ${{ inputs.use-tox == 'true' }}
    
    - name: Test with pytest.
      run: poetry run pytest
      shell: bash
      if: ${{ inputs.use-tox == 'false' }}

    # - run: $GITHUB_ACTION_PATH/main.sh
    #   shell: bash

    # - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
    #   shell: bash

    # - id: random-number-generator
    #   run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
    #   shell: bash
