name: Quality check.
author: Harshad Hegde <hhegde@lbl.gov>
description: Quality check for a given project.
inputs:
  python-version:

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3.0.2
      
    - name: Set up Python ${{ inputs.python-versions }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ inputs.python-version }}
    
    - run: $GITHUB_ACTION_PATH/main.sh
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
