name: Quality check.
author: Harshad Hegde <hhegde@lbl.gov>
description: Quality check for a given project.
inputs:
  python-versions:
    description: Python version(s).
  tox:
    description: Run tox
    default: "false"
outputs:
  random-number:
    description: Random number
    value: ${{ steps.random-number-generator.outputs.random-number }}

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v2.5.0

    - name: Set up Python ${{ inputs.python-versions }}
      uses: actions/setup-python@v4.3.0
      with:
        python-version: ${{ inputs.python-versions }}

    - name: Install Poetry
      run: pip install poetry
      shell: bash

    - name: Install dependencies
      run: poetry install --no-interaction
      shell: bash
    
    - name: Check code quality with flake8
      run: poetry run tox -e flake8
      shell: bash
      if: ${{ inputs.tox == true }}

    - name: Check static typing with MyPy
      run: poetry run tox -e mypy
      shell: bash
      if: ${{ inputs.tox == true }}

    - name: Test with pytest and generate coverage file
      run: poetry run tox -e py
      shell: bash
      if: ${{ inputs.tox == true }}
    
    - name: Test with pytest and generate coverage file
      run: poetry run pytest
      shell: bash
      if: ${{ inputs.tox == false }}
    
    - run: $GITHUB_ACTION_PATH/main.sh
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash

    - id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash
